### ISSUE TITLE
SettingWithCopyWarning:

### ISSUE THREAD

**Issue by Draavos** [rglez/bitclust#4]
when I run the Bitclust , there is have error show up :

/home/tuan/miniconda3/envs/bitclust/lib/python3.10/site-packages/bitclust-0.0.12-py3.10.egg/bitclust/main.py:400: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame
See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
NORMAL TERMINATION :J

Please help me to solve this problem. Thank you so much!

**Comment by rglez** [comment]
Hello,

This message is not an error but a warning from the pandas library. They
will deprecate a behaviour for value assignment but it is not a bug.

You can go to the link thrown for details.

Warmly,

Roy

**Comment by Draavos** [comment]
Thank you so much, I got the result. Thank you so much for the good Software.

**Comment by rglez** [comment]
Happy to see that it is useful :) Do not hesitate if any other issue arises.

Roy
